spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  zipkin:                            #将服务注册到追踪中心服务中
    base-url: http://localhost:9411

server:
  port: 8765
#开启feign自带的熔断器
feign:
  hystrix:
    enabled: true

eureka:               #找到eureka并注册服务
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/