spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html

server:
  port: 8766
#开启feign自带的熔断器
feign:
  hystrix:
    enabled: true

eureka:               #找到eureka并注册服务
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/